image: node:lts-buster # https://hub.docker.com/_/node

before_script:
  - node --version
  - npm --version
  - npm install

pages:
  script:
  - npm run build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
